# .github/dependabot.yml
version: 2

updates:
  # 1) Python deps managed by uv (updates pyproject.toml + uv.lock)
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels: [ "deps", "uv" ]
    commit-message:
      prefix: "⬆"
      include: "scope"
    # Group related updates to reduce PR count while keeping risk reasonable
    groups:
      test-deps:
        patterns:
          - "pytest"
          - "pytest-*"
          - "coverage*"
          - "pytest-cov"
        update-types: [ "minor", "patch" ]
      lint-type:
        patterns:
          - "ruff*"
          - "types-*"
        update-types: [ "minor", "patch" ]
      docs:
        patterns:
          - "mkdocs*"
          - "mkdocstrings*"
          - "mkdocs-redirects"
          - "mkdocs-autorefs"
          - "mkdocs-exclude"
          - "mkdocs-llmstxt"
        update-types: [ "minor", "patch" ]

  # 2) GitHub Actions (digest/patch/minor grouped; majors separate)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels: [ "deps", "actions" ]
    commit-message:
      prefix: "⬆"
      include: "scope"
    groups:
      gha-minor-patch:
        patterns: [ "*" ]
        update-types: [ "digest", "patch", "minor" ]
