site_name: Air
site_url: http://feldroy.github.io/air/
repo_url: https://github.com/feldroy/air
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Air Tags: air-tags.md
  - About:  
    - about/index.md
    - about/history.md    
    - about/alternatives.md
  - API Reference:
    - api/index.md
    - Applications: api/applications.md    
    - CLI: api/cli.md
    - Generator: api/generator.md
    - Requests: api/requests.md
    - Responses: api/responses.md
    - SVG: api/svg.md
    - Tags: api/tags.md
    - Templates: api/templates.md
  - Static Sites: static-sites.md    
theme:
  name: material
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking    
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tabs    
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true  
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            show_source: true
