site_name: Air
site_url: http://feldroy.github.io/air/
repo_url: https://github.com/feldroy/air
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Concepts:
    - concepts/index.md
    - concepts/air_tags.md
    - concepts/escaping_html.md
    - concepts/forms.md
    - concepts/jinja.md
    - concepts/layouts.md
  - Reference:
    - api/index.md
    - Applications: api/applications.md
    - Background Tasks: api/background.md    
    - CLI: api/cli.md
    - Generator: api/generator.md
    - Layouts: api/layouts.md
    - Requests: api/requests.md
    - Responses: api/responses.md
    - SVG: api/svg.md
    - Tags: api/tags.md
    - Templates: api/templates.md  
  - About:  
    - about/index.md
    - about/history.md    
    - about/alternatives.md    
theme:
  name: material
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking    
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tabs    
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true  
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            show_source: true
            unwrap_annotated: true
            members_order: source
            separate_signature: true
            # docstring_options:
            #   ignore_init_summary: true            
            merge_init_into_class: true