site_name: Air
site_url: http://feldroy.github.io/air/
repo_url: https://github.com/feldroy/air
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Reference:
    - ref/index.md
    - Applications: ref/applications.md    
    - CLI: ref/cli.md
    - Generator: ref/generator.md
    - Layouts: ref/layouts.md
    - Requests: ref/requests.md
    - Responses: ref/responses.md
    - SVG: ref/svg.md
    - Tags: ref/tags.md
    - Templates: ref/templates.md  
  - About:  
    - about/index.md
    - about/history.md    
    - about/alternatives.md    
theme:
  name: material
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking    
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tabs    
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true  
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            show_source: true
