site_name: Air
site_url: https://air.feldroy.com
repo_url: https://github.com/feldroy/air
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Static Sites: static-sites.md
  - API Reference:
    - CLI: api/cli.md
    - Generator: api/generator.md
    - Requests: api/requests.md
    - Responses: api/responses.md
    - SVG: api/svg.md
    - Tags: api/tags.md
    - Templates: api/templates.md
theme:
  name: material
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.instant
    - navigation.instant.prefetch
    - search.suggest
    - search.highlight
    - search.share
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true  
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            show_source: true