[project]
name = "airdocs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "air",
    "eidosui",
    "fastapi[standard]>=0.115.14",
    "marimo>=0.14.10",
    "mkdocstrings[python]>=0.29.1",
]

[tool.uv.sources]
air = { path = "../air", editable = true }
eidosui = { path = "../EidosUI", editable = true }
