# .github/workflows/ci-overview.yml
name: CI Overview

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

# Keep one live run per PR; cancel stale ones
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

# Least privilege for the whole workflow
permissions:
  contents: read
  checks: read
  actions: read
  pull-requests: write

jobs:
  overview:
    name: CI Overview
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # 1) Wait until PR checks settle; fail if anything is failing/pending
      - name: Wait for checks
        id: wait
        uses: wechuli/allcheckspassed@e22f45a4f25f4cf821d1273705ac233355400db1 # v1.2.0
        with:
          delay: '1'                # minutes before first poll
          retries: '15'             # 15 polls
          polling_interval: '1'     # minutes between polls
          fail_fast: false          # wait for all to complete before reporting
          # Comma-separated names or regex (meaning: regular expression) patterns:
          checks_exclude: 'skipped,CI Overview, Coverage with Codecov, codecov/patch'
          show_job_summary: 'true'  # nice table in the job Summary tab
      - name: Fetch CI Overview summary_raw
        id: fetch-summary
        uses: fjogeleit/http-request-action@v1.16.4
        with:
          method: GET
          url: ${{ steps.wait.outputs.summary_url }} # your full summary_raw URL here
          timeout: 15000
          ignoreStatusCodes: '401,403,404'
      # Example: post it with add-pr-comment (render as code block)
      - name: Comment summary_raw
        if: always()
        uses: mshick/add-pr-comment@v2
        with:
          message-id: ci-overview:summary-raw
          preformatted: true
          message: ${{ steps.fetch-summary.outputs.response }}
