# .github/workflows/ci-overview.yml
name: CI Overview

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: read
  actions: read
  pull-requests: write

jobs:
  overview:
    name: CI Overview
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # 1) Wait until PR checks settle; FAIL if anything is failing/pending
      - name: Wait for checks
        id: wait
        uses: wechuli/allcheckspassed@e22f45a4f25f4cf821d1273705ac233355400db1 # v1.2.0
        with:
          delay: '1'
          retries: '15'
          polling_interval: '1'
          fail_fast: false
          checks_exclude: 'skipped,CI Overview,Coverage with Codecov,codecov/patch'
          show_job_summary: 'true'   # writes to $GITHUB_STEP_SUMMARY
      # 2) Export $GITHUB_STEP_SUMMARY
      - name: Expose summary path for later steps
        run: echo "SUMMARY_PATH=$GITHUB_STEP_SUMMARY" >> "$GITHUB_ENV"
      # 3) Post the raw HTML/Markdown as a sticky PR comment (code block)
      - name: Comment summary_raw (content)
        if: ${{ always() && env.SUMMARY_PATH != '' }}
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2.8.2
        with:
          message-id: ci-overview:summary-raw
          message-path: ${{ env.SUMMARY_PATH }}
