# .github/workflows/ci-overview.yml
name: CI Overview

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: read
  actions: read
  pull-requests: write

jobs:
  overview:
    name: CI Overview
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # 1) Wait until PR checks settle; FAIL if anything is failing/pending
      - name: Wait for checks
        id: wait
        uses: wechuli/allcheckspassed@v1.2.0
        with:
          delay: '1'
          retries: '15'
          polling_interval: '1'
          fail_fast: false
          checks_exclude: 'skipped,CI Overview,Coverage with Codecov,codecov/patch'
          show_job_summary: 'true'

      # 2) Read THIS job’s summary (same content as the /summary_raw page)
      - name: Read job summary (raw)
        if: always()
        id: read-summary
        uses: juliangruber/read-file-action@v1
        with:
          path: ${{ env.GITHUB_STEP_SUMMARY }}

      # 3a) Post the raw HTML/Markdown as a sticky PR comment (code block)
      - name: Comment summary_raw (content)
        if: ${{ always() && steps.read-summary.outputs.content != '' }}
        uses: mshick/add-pr-comment@v2
        with:
          message-id: ci-overview:summary-raw
          preformatted: true
          message: ${{ steps.read-summary.outputs.content }}

      # 3b) Fallback note when the summary is empty (rare)
      - name: Comment summary_raw (fallback)
        if: ${{ always() && steps.read-summary.outputs.content == '' }}
        uses: mshick/add-pr-comment@v2
        with:
          message-id: ci-overview:summary-raw
          preformatted: true
          message: |
            Bottom line: unavailable (meaning: cannot be shown). The job summary file was empty for this run.
