# .github/workflows/ci-overview.yml
name: CI Overview

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

# Keep one live run per PR; cancel stale ones
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

# Least privilege for the whole workflow
permissions:
  contents: read
  checks: read
  actions: read
  pull-requests: write

jobs:
  overview:
    name: CI Overview
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # 1) Wait until PR checks settle; fail if anything is failing/pending
      - name: Wait for checks
        uses: wechuli/allcheckspassed@e22f45a4f25f4cf821d1273705ac233355400db1 # v1.2.0
        with:
          delay: '1'                # minutes before first poll
          retries: '15'             # 15 polls
          polling_interval: '1'     # minutes between polls
          fail_fast: false          # wait for all to complete before reporting
          # Comma-separated names or regex (meaning: regular expression) patterns:
          checks_exclude: 'skipped,CI Overview, Coverage with Codecov, codecov/patch'
          show_job_summary: 'true'  # nice table in the job Summary tab

      # 2) Always post/update a sticky PR comment with one-line per check
      - name: CI overview (sticky PR comment)
        uses: ipdxco/sorted-pr-checks@e93469d12abf23967b6346a76599e1a087161c82 # v2.0.0
        with:
          repository: ${{ github.repository }}
          pull_number: ${{ github.event.pull_request.number }}
          # Built-in templates: sorted_by_result | grouped_by_result | unsuccessful_only
          template: grouped_by_result
          identifier: 'CI Overview'      # sticky (updates same comment)
          token: ${{ secrets.GITHUB_TOKEN }}
