# .github/workflows/python-package.yml
# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# CI using uv + just, with minimal/noise-free logs:
# - Colors forced inside a tiny wrapper script (not via step `env:`), so they don’t appear in the log header.
# - No echo/group commands shown.
# - Shared bootstrap steps are DRY via YAML anchors.

name: Python package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - &checkout {uses: actions/checkout@v5}
      - &setup_uv
        name: Install uv (with cache)
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
      - name: Install just
        uses: taiki-e/install-action@just
      - name: QA (format, lint, types) (via just, uv, ruff and ty)
        run: just qa
      - name: Test on 3.10–>3.13 (via just, uv, pytest and pytest-rich)
        run: just testall
