# .github/workflows/python-package.yml
# CI using uv + just; shared steps are defined once via YAML anchors.
name: Python package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Define shared steps once (this job never runs).
  _shared:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - &checkout
        name: Checkout
        uses: actions/checkout@v5

      - &setup_uv
        name: Install uv (with cache) and set Python 3.13
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
          python-version: "3.13"

      - &install_just
        name: Install just
        uses: taiki-e/install-action@just

  qa:
    name: QA (format, lint, types, tests)
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setup_uv
      - *install_just
      - name: Run just qa
        run: just qa

  test-all:
    name: Test on 3.10–3.13 (via just)
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setup_uv
      - *install_just
      - name: Run just testall
        run: just testall
