# .github/workflows/python-package.yml
# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# CI using uv + just, with minimal/noise-free logs:
# - Colors forced inside a tiny wrapper script (not via step `env:`), so they don’t appear in the log header.
# - No echo/group commands shown.
# - Shared bootstrap steps are DRY via YAML anchors.

name: Python package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Define shared bootstrap once (never runs; used for anchors).
  _shared:
    if: ${{ false }}
    name: skipped
    runs-on: ubuntu-latest
    steps:
      - &checkout {uses: actions/checkout@v5}
      - &setup_uv
        name: Install uv (with cache)
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
      - &install_just
        name: Install just
        uses: taiki-e/install-action@just

  qa:
    name: QA (format, lint, types) (via just, uv, ruff and ty)
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setup_uv
      - *install_just
      - name: QA (format, lint, types) (via just, uv, ruff and ty)
        run: just qa
  test-all:
    name: Test on 3.10–>3.13 (via just, uv, pytest and pytest-rich)
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setup_uv
      - *install_just
      - name: Test on 3.10–>3.13 (via just, uv, pytest and pytest-rich)
        run: just test-all
  test-coverage:
    name: Measuring Coverage (via just, uv, pytest, pytest-cov and coverage[toml])
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setup_uv
      - *install_just
      - name: Measuring Coverage (via just, uv, pytest, pytest-cov and coverage[toml])
        run: just test-coverage
